import { register } from "swiper/element";

export const route = {
  home: "/",
  login: "/login",
  register: "/register",
  policy: "/policy",
  bst: "/bst",
  productDetail: "/product/:productId",
  payment: "/payment",
  orderSuccess: "/order-success",
  orderFailed: "/order-failed",
  service: "/service",
  aboutUs: "/about-us",
  admin: "/admin",
  adminProducts: "/admin/products",
  adminOrders: "/admin/orders",
  adminCategories: "/admin/categories",
  adminBrands: "/admin/brands",
  adminRentalRules: "/admin/rental-rules",
  adminUsers: "/admin/users",
  adminSettings: "/admin/settings",
  cart: "/cart",
  profile: "/profile",
  myOrders: "/my-orders",
};
